### ISSUE TITLE
Alignment between data and LibriTTS source?

### ISSUE THREAD

**Issue by dreamk73** [Helsinki-NLP/prosody#1]
I read your paper with great interest and am looking to test out several methods to predict prominence and phrasing from text. I was wondering if it is possible to figure out where the data in your annotated directory came from in the LibriTTS corpus? Is there an easy way to find the corresponding audio and speaker ID?

**Comment by aarnetalman** [comment]
Thanks for the great question and suggestion. I’ll modify the data format to include information about the source in LibriTTS (file name). I will try to get this done sometime next week.

**Comment by aarnetalman** [comment]
I updated the dataset to include the source file name before each sentence: `<file>    file_name.txt`. I also updated `prosody_dataset.py` accordingly. Hope this helps.

**Comment by dreamk73** [comment]
Thanks!
